python2.7:
  image: python:2.7-stretch
  script:
    - pip install .[test]
    - pip install .
    - coverage run -m py.test
    - pylint --rcfile .pylintrc -E tuir/
    - coverage report

python3.5:
  image: python:3.5-stretch
  script:
    - pip install .[test]
    - pip install .
    - coverage run -m py.test
    - pylint --rcfile .pylintrc -E tuir/
    - coverage report

python3.6:
  image: python:3.6-stretch
  script:
    - pip install .[test]
    - pip install .
    - coverage run -m py.test
    - pylint --rcfile .pylintrc -E tuir/
    - coverage report

python3.7:
  image: python:3.7-stretch
  script:
    - pip install .[test]
    - pip install .
    - coverage run -m py.test
    - pylint --rcfile .pylintrc -E tuir/
    - coverage report

python3.8:
  image: python:3.8-stretch
  script:
    - pip install .[test]
    - pip install .
    - coverage run -m py.test
    - pylint --rcfile .pylintrc -E tuir/
    - coverage report
